#pragma once

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define SPLASH_STATE_SHOW_TIME 3.0

#define SPLASH_SCENE_BACKGROUND_FILEPATH ""
#define MAIN_MENU_BACKGROUND_FILEPATH ""

#define GAME_TITLE_FILEPATH ""
#define PLAY_BUTTON_FILEPATH ""
